# Generated by Django 4.1.3 on 2022-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_nickname_user_user_name_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
